### ISSUE TITLE
Quotation needed for labels

### ISSUE THREAD

**Issue by gustavosr98** [canonical/prometheus-scrape-target-k8s-operator#52]
### Bug Description

I get an error when prometheus tries to validate the yaml configuration of a scrape target with labels without `'` in the values

### To Reproduce

```bash
juju deploy -m cos prometheus-scrape-target-k8s prometheus-scrape-target-gpu-a \
    --channel 1/stable \
    --base ubuntu@20.04 \
    --config job_name=gpu-metrics-gpu-1 \
    --config labels="dns_name:k8s-cluster-ai-1.maas,kubernetes_node:k8s-cluster-ai-1" \
    --config scheme=http \
    --config metrics_path="/metrics" \
    --config tls_config_insecure_skip_verify=true \
    --config targets="10.0.85.90:32094"
juju relate -m cos prometheus-scrape-target-gpu-a prometheus
```

### Environment

Juju 3.6.5
Canonical Kubernetes 1.32

prometheus-scrape-target-k8s  1/stable        34
prometheus-k8s (2.52.0)               1/stable       247

### Relevant log output

```bash
# juju show-unit prometheus-scrape-target-gpu-a/0
prometheus-scrape-target-gpu-a/0:
  workload-version: n/a
  opened-ports: []
  charm: ch:amd64/prometheus-scrape-target-k8s-34
  leader: true
  life: alive
  relation-info:
  - relation-id: 53
    endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data:
      event: '{"scrape_job_errors": "Command ''[''/var/lib/juju/agents/unit-prometheus-0/charm/cos-tool-amd64'',
        ''validate-config'', ''/tmp/tmpox1_jb20'']'' returned non-zero exit status
        1."}'
    related-units:
      prometheus/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.99/32
          ingress-address: 10.152.183.99
          private-address: 10.152.183.99
  provider-id: prometheus-scrape-target-gpu-a-0
  address: 10.1.0.108
```

I tried to check inside the po the config it gets but I was on the wrong pod
Looks like the pod that validates the config is prometheus and not the scrape-target
So I tried to check the configuration it was trying to generate

```bash
# juju show-unit prometheus/0 | less

[..]
  - relation-id: 53
    endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data:
      scrape_jobs: '[{"job_name": "juju_cos_f15f0cd_prometheus-scrape-target-gpu-a_gpu-metrics-gpu-1",
        "static_configs": [{"targets": ["10.0.85.90:32094"], "labels": {"dns_name":
        "k8s-cluster-ai-1.maas", "kubernetes_node": "k8s-cluster-ai-1"}}],
        "metrics_path": "/metrics", "scheme": "http", "tls_config": {"insecure_skip_verify":
        true}}]'
    related-units:
      prometheus-scrape-target-gpu-a/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.42/32
          ingress-address: 10.152.183.42
          private-address: 10.152.183.42
```

Which looks like translates from json to yalm like this

```yaml
job_name: juju_cos_f15f0cd_prometheus-scrape-target-gpu-a_gpu-metrics-gpu-1
static_configs:
  - targets:
      - '10.0.85.90:32094'
    labels:
      dns_name: k8s-cluster-ai-1.maas
      kubernetes_node: k8s-cluster-ai-1
metrics_path: /metrics
scheme: http
tls_config:
  insecure_skip_verify: true
```

### Additional context

After updating the values of lables to
```bash
juju config prometheus-scrape-target-gpu-a labels="dns_name:'k8s-cluster-ai-1.maas',kubernetes_node:'k8s-cluster-ai-1'"
```

And removing and re-adding the relation between the scrape target and prometheus
Then it works

**Comment by sed-i** [comment]
Huh:
```diff
-labels="dns_name:k8s-cluster-ai-1.maas,kubernetes_node:k8s-cluster-ai-1"
+labels="dns_name:'k8s-cluster-ai-1.maas',kubernetes_node:'k8s-cluster-ai-1'"
```

Odd that you needed extra quotes because [parsing](https://github.com/canonical/prometheus-scrape-target-k8s-operator/blob/596d681be7f37af34452e67b93c36539fb8efa2c/src/charm.py#L180) even without them it's valid yaml
```python
>>> print(yaml.safe_dump(dict([p.split(":") for p in "dns_name:x2o-k8s-cluster-ai-1.maas,kubernetes_node:x2o-k8s-cluster-ai-1".split(",")])))
dns_name: x2o-k8s-cluster-ai-1.maas
kubernetes_node: x2o-k8s-cluster-ai-1
```

vs. with quote
```python
>>> print(yaml.safe_dump(dict([p.split(":") for p in "dns_name:'x2o-k8s-cluster-ai-1.maas',kubernetes_node:'x2o-k8s-cluster-ai-1'".split(",")])))
dns_name: '''x2o-k8s-cluster-ai-1.maas'''
kubernetes_node: '''x2o-k8s-cluster-ai-1'''
```

Maybe there are "yaml pitfalls" here. Fwiw, the original does pass yaml validation. Need to investigate.

**Comment by sinapah** [comment]
Hi @gustavosr98,

I've attempted to reproduce this using the following bundle, but I'm not able to.
```yaml
juju export-bundle                                                                                                                                                         
bundle: kubernetes
applications:
  prom:
    charm: prometheus-k8s
    channel: dev/edge
    revision: 315
    resources:
      prometheus-image: 155
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
  scrape:
    charm: prometheus-scrape-target-k8s
    channel: dev/edge
    revision: 42
    scale: 1
    options:
      labels: dns_name:k8s-cluster-ai-1.maas,kubernetes_node:k8s-cluster-ai-1
      metrics_path: /metrics
      params: '{"auth": ["snmp_v3"], "module": ["if_mib_if_name", "if_mib"]}'
      scheme: http
      targets: 10.0.0.0:3000
    constraints: arch=amd64
    trust: true
relations:
- - scrape:metrics-endpoint
  - prom:metrics-endpoint

```

Even if I try with Prom and Prometheus Scrape channel 1/stable with the revs that you had, I can't get this to occur again.

I'll close this issue for now, but feel free to reopen if the issue comes up again.
